package org.kiwiproject.changelog

import java.util.regex.Pattern

fun formatChangeLog(contributors: Set<String>,
                    tickets: List<Ticket>,
                    commitCount: Int,
                    version: String,
                    previousRev: String,
                    githubRepoUrl: String,
                    date: String) : String {

    val template = """
        @header@
        
        #### @version@
        - @date@ - [@commitCount@ commit(s)](@repoUrl@/compare/@previousRev@...@newRev@) by @contributors@
        @improvements@
    """.trimIndent()

    val logData = mapOf(
        "header" to "<sup><sup>*Changelog generated by [KiwiProject Changelog Plugin](https://github.com/kiwiproject/kiwiproject-changelog)*</sup></sup>",
        "version" to version,
        "date" to date,
        "commitCount" to "$commitCount",
        "repoUrl" to githubRepoUrl,
        "previousRev" to previousRev,
        "newRev" to "v$version",
        "contributors" to contributors.joinToString(", "),
        "improvements" to formatImprovements(tickets)
    )

    return replaceTokens(template, logData)
}

fun formatImprovements(tickets: List<Ticket>) : String {
    if (tickets.isEmpty()) {
        return " - No notable improvements. No pull requests (issues) were referenced from commits."
    }

    return tickets.joinToString("\n") { ticket -> " - ${ticket.title} [(#${ticket.id})](${ticket.url})" }
}

fun replaceTokens(template: String, data: Map<String, String>) : String {
    val pattern = Pattern.compile("@(.+?)@")
    val matcher = pattern.matcher(template)
    val buffer = StringBuffer()

    while (matcher.find()) {
        val replacement: String? = data.get(matcher.group(1))
        if (replacement != null) {
            matcher.appendReplacement(buffer, "")
            buffer.append(replacement)
        }
    }
    matcher.appendTail(buffer)
    return buffer.toString()
}
