package org.kiwiproject.changelog

import org.kiwiproject.changelog.config.ChangelogConfig
import org.kiwiproject.changelog.config.GitRepoConfig
import java.util.regex.Pattern

fun formatChangeLog(contributors: Set<String>,
                    tickets: List<Ticket>,
                    commitCount: Int,
                    gitRepoConfig: GitRepoConfig,
                    changelogConfig: ChangelogConfig,
                    githubRepoUrl: String) : String {

    val template = """
        @header@
        
        ## @version@
        - @date@ - [@commitCount@ commit(s)](@repoUrl@/compare/@previousRev@...@newRev@) by @contributors@
        @improvements@
    """.trimIndent()

    val logData = mapOf(
        "header" to "<sup><sup>*Changelog generated by [KiwiProject Changelog Plugin](https://github.com/kiwiproject/kiwiproject-changelog)*</sup></sup>",
        "version" to changelogConfig.version,
        "date" to changelogConfig.dateString,
        "commitCount" to "$commitCount",
        "repoUrl" to githubRepoUrl,
        "previousRev" to gitRepoConfig.previousRevision,
        "newRev" to "v${gitRepoConfig.revision}",
        "contributors" to contributors.joinToString(", "),
        "improvements" to formatImprovements(tickets, changelogConfig.categoryConfig.categoryOrder)
    )

    return replaceTokens(template, logData)
}

fun formatImprovements(tickets: List<Ticket>, categoryOrder: List<String>?) : String {
    if (tickets.isEmpty()) {
        return " - No notable improvements. No pull requests (issues) were referenced from commits."
    }

    val groupedTickets = tickets.groupBy { it.category }.toSortedMap()

    val categories = categoryOrder ?: groupedTickets.keys
    var improvementText = ""

    for (category in categories) {
        if (!groupedTickets.containsKey(category)) {
            continue
        }

        improvementText += "## $category\n"

        for (ticket in groupedTickets[category] ?: listOf()) {
            improvementText += "* ${ticket.title} [(#${ticket.id})](${ticket.url})\n"
        }
    }

    return improvementText
}

fun replaceTokens(template: String, data: Map<String, String>) : String {
    val pattern = Pattern.compile("@(.+?)@")
    val matcher = pattern.matcher(template)
    val buffer = StringBuffer()

    while (matcher.find()) {
        val replacement: String? = data.get(matcher.group(1))
        if (replacement != null) {
            matcher.appendReplacement(buffer, "")
            buffer.append(replacement)
        }
    }
    matcher.appendTail(buffer)
    return buffer.toString()
}
